-- **주의**: 이 스크립트는 DDL 없이 DML (데이터 삽입)만 수행하며,
-- 기존 테스트 데이터를 삭제하고 재삽입하는 방식으로 실행됩니다.
-- 이 스크립트를 실행하기 전에 모든 테이블(MEMBER_INFO, HOSPITAL_INFO 포함)과 시퀀스가 이미 생성되어 있어야 합니다.

-- ===============================================
-- 0. 기존 테스트 데이터 초기화 (재실행을 위한 안전장치)
-- ===============================================
DELETE FROM HEALTH_DATA;
DELETE FROM MEDICATION;
DELETE FROM DIAGNOSIS;
DELETE FROM THRESHOLD_SETTING WHERE MEMBER_ID = 'M001'; -- 특정 회원의 설정만 삭제
DELETE FROM HOSP_SYNC_DATA;

COMMIT;

-- ===============================================
-- 1. 기초 참조 데이터 보강 (부모 키 충족을 위해 반드시 필요)
-- 중복 삽입을 막기 위해 PL/SQL 블록 사용
-- ===============================================

BEGIN
    -- 1-1. MEMBER_INFO: 'M001' 홍길동 회원이 존재하지 않을 경우에만 삽입
    INSERT INTO MEMBER_INFO (MEMBER_ID, NAME, EMAIL, PASSWORD, BIRTH_DATE)
    SELECT 'M001', '홍길동', 'hong_test@phr.com', '1234', TO_DATE('1990-05-15', 'YYYY-MM-DD')
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM MEMBER_INFO WHERE MEMBER_ID = 'M001');
    
    -- 1-2. HOSPITAL_INFO: 'H001', 'H002' 병원 코드가 존재하지 않을 경우에만 삽입
    INSERT INTO HOSPITAL_INFO (HOSP_CODE, HOSP_NAME, HOSP_ADDRESS)
    SELECT 'H001', '서울 종합 병원', '서울특별시'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HOSPITAL_INFO WHERE HOSP_CODE = 'H001');

    INSERT INTO HOSPITAL_INFO (HOSP_CODE, HOSP_NAME, HOSP_ADDRESS)
    SELECT 'H002', '경기 대학 병원', '경기도 수원시'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HOSPITAL_INFO WHERE HOSP_CODE = 'H002');

    -- 1-3. MEASURE_ITEM: 필요한 항목 코드가 존재하지 않을 경우에만 삽입
    INSERT INTO MEASURE_ITEM (ITEM_CODE, ITEM_NAME, UNIT)
    SELECT 'SBP01', '수축기 혈압', 'mmHg'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM MEASURE_ITEM WHERE ITEM_CODE = 'SBP01'); -- **이 부분이 해결책입니다.**

    INSERT INTO MEASURE_ITEM (ITEM_CODE, ITEM_NAME, UNIT)
    SELECT 'BS01', '혈당', 'mg/dL'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM MEASURE_ITEM WHERE ITEM_CODE = 'BS01');

    INSERT INTO MEASURE_ITEM (ITEM_CODE, ITEM_NAME, UNIT)
    SELECT 'WT01', '체중', 'kg' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MEASURE_ITEM WHERE ITEM_CODE = 'WT01');
    
    INSERT INTO MEASURE_ITEM (ITEM_CODE, ITEM_NAME, UNIT)
    SELECT 'HT01', '키', 'cm' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MEASURE_ITEM WHERE ITEM_CODE = 'HT01');
    
    INSERT INTO MEASURE_ITEM (ITEM_CODE, ITEM_NAME, UNIT)
    SELECT 'HR01', '심박수', 'bpm' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MEASURE_ITEM WHERE ITEM_CODE = 'HR01');

END;
/
COMMIT;


-- ===============================================
-- 2. 테스트용 임계치 설정 데이터 추가 (M001 사용)
-- ===============================================

-- SBP01 (수축기 혈압)에 대한 임계치 설정
INSERT INTO THRESHOLD_SETTING (SET_ID, MEMBER_ID, ITEM_CODE, UPPER_BOUND, LOWER_BOUND, REG_DATE)
VALUES (SEQ_THRESHOLD_ID.NEXTVAL, 'M001', 'SBP01', 140.0, 90.0, SYSDATE);

-- BS01 (혈당)에 대한 임계치 설정
INSERT INTO THRESHOLD_SETTING (SET_ID, MEMBER_ID, ITEM_CODE, UPPER_BOUND, LOWER_BOUND, REG_DATE)
VALUES (SEQ_THRESHOLD_ID.NEXTVAL, 'M001', 'BS01', 100.0, 70.0, SYSDATE);


-- ===============================================
-- 3. 테스트 진료 기록 및 건강 데이터 추가 (M001 사용)
-- ===============================================

DECLARE
    V_CURRENT_SYNC_ID NUMBER;
BEGIN

    -- 3-1. 첫 번째 진료 기록 (2025-10-01) - 혈압 정상, 혈당 정상
    SELECT HOSP_SYNC_SEQ.NEXTVAL INTO V_CURRENT_SYNC_ID FROM DUAL;
    
    INSERT INTO HOSP_SYNC_DATA (SYNC_ID, MEMBER_ID, HOSP_CODE, SYNC_DATE)
    VALUES (V_CURRENT_SYNC_ID, 'M001', 'H001', TO_DATE('2025-10-01', 'YYYY-MM-DD'));
    
    -- 진단
    INSERT INTO DIAGNOSIS VALUES (DIAGNOSIS_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, 'I10', '본태성(일차성) 고혈압', TO_DATE('2025-10-01', 'YYYY-MM-DD'));
    
    -- 투약
    INSERT INTO MEDICATION VALUES (MEDICATION_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, '혈압약A', '10mg', TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-31', 'YYYY-MM-DD'));
    
    -- 건강 데이터
    INSERT INTO HEALTH_DATA (HEALTH_DATA_ID, SYNC_ID, ITEM_CODE, MEASURE_VALUE, MEASURE_UNIT, MEASURE_DATE)
    VALUES (HEALTH_DATA_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, 'SBP01', 125.00, 'mmHg', TO_DATE('2025-10-01', 'YYYY-MM-DD'));
    INSERT INTO HEALTH_DATA (HEALTH_DATA_ID, SYNC_ID, ITEM_CODE, MEASURE_VALUE, MEASURE_UNIT, MEASURE_DATE)
    VALUES (HEALTH_DATA_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, 'BS01', 95.00, 'mg/dL', TO_DATE('2025-10-01', 'YYYY-MM-DD'));
    
    
    -- 3-2. 두 번째 진료 기록 (2025-11-15) - 혈압 이상치 발생 (155.00)
    SELECT HOSP_SYNC_SEQ.NEXTVAL INTO V_CURRENT_SYNC_ID FROM DUAL;
    
    INSERT INTO HOSP_SYNC_DATA (SYNC_ID, MEMBER_ID, HOSP_CODE, SYNC_DATE)
    VALUES (V_CURRENT_SYNC_ID, 'M001', 'H002', TO_DATE('2025-11-15', 'YYYY-MM-DD'));
    
    -- 진단
    INSERT INTO DIAGNOSIS VALUES (DIAGNOSIS_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, 'E11', '제2형 당뇨병', TO_DATE('2025-11-15', 'YYYY-MM-DD'));
    
    -- 건강 데이터
    INSERT INTO HEALTH_DATA (HEALTH_DATA_ID, SYNC_ID, ITEM_CODE, MEASURE_VALUE, MEASURE_UNIT, MEASURE_DATE)
    VALUES (HEALTH_DATA_SEQ.NEXTVAL, V_CURRENT_SYNC_ID, 'SBP01', 155.00, 'mmHg', TO_DATE('2025-11-15', 'YYYY-MM-DD'));

END;
/
-- 4. 최종 커밋
COMMIT;