CREATE TABLE HEALTH_DATA (
    DATA_ID NUMBER(10) PRIMARY KEY,
    MEMBER_ID NUMBER(10) NOT NULL,
    ITEM_CODE VARCHAR2(20) NOT NULL,
    MEASURE_VALUE NUMBER(8, 2),
    MEASURE_DATE DATE DEFAULT SYSDATE,
    MEMO VARCHAR2(500),
    CONSTRAINT FK_HDATA_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER_INFO(MEMBER_ID)
);

CREATE SEQUENCE SEQ_HEALTH_DATA_ID START WITH 1 INCREMENT BY 1;

COMMIT;