﻿DROP TABLE HEALTH_VALUE;

CREATE TABLE HEALTH_VALUE (
    VALUE_CODE NUMBER(10) PRIMARY KEY,
    VALUE_NAME VARCHAR2(50) NOT NULL,
    CURRENT_VALUE NUMBER(10,2) NOT NULL,
    MIN_WARNING NUMBER(10,2) NOT NULL,
    MAX_WARNING NUMBER(10,2) NOT NULL,
    MEASURE_DATE DATE DEFAULT SYSDATE
);

INSERT INTO HEALTH_VALUE VALUES (1, '혈압', 160, 90, 140, SYSDATE);
INSERT INTO HEALTH_VALUE VALUES (2, '혈압', 120, 90, 140, SYSDATE);
INSERT INTO HEALTH_VALUE VALUES (3, '혈당', 210, 70, 160, SYSDATE);
INSERT INTO HEALTH_VALUE VALUES (4, '혈당', 110, 70, 160, SYSDATE);
INSERT INTO HEALTH_VALUE VALUES (5, '심박수', 40, 60, 100, SYSDATE);

COMMIT;