-- 1. 기존 테이블이 있다면 삭제 (순서 중요: 외래 키가 걸린 테이블부터 삭제)
DROP TABLE HEALTH_DATA;
DROP TABLE MEDICATION;
DROP TABLE DIAGNOSIS;
DROP TABLE HOSP_SYNC_DATA;
DROP TABLE HOSPITAL_INFO;
DROP TABLE MEASURE_ITEM;
DROP TABLE MEMBER_INFO;

-- 2. 핵심 테이블 생성
-- 1) MEMBER_INFO (회원 정보) - 테스트용 회원 ID M001을 위해 필요
CREATE TABLE MEMBER_INFO (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    NAME      VARCHAR2(50) NOT NULL,
    BIRTH_DATE DATE
);

-- 2) HOSPITAL_INFO (병원 정보) - 드롭다운 목록을 위해 필요
CREATE TABLE HOSPITAL_INFO (
    HOSP_CODE VARCHAR2(20) PRIMARY KEY,
    HOSP_NAME VARCHAR2(100) NOT NULL,
    HOSP_ADDRESS VARCHAR2(200)
);

-- 3) HOSP_SYNC_DATA (병원 연동 데이터) - 회원/병원/진료 기록을 묶는 핵심 테이블
CREATE TABLE HOSP_SYNC_DATA (
    SYNC_ID     NUMBER(10) PRIMARY KEY,
    MEMBER_ID   VARCHAR2(20) NOT NULL,
    HOSP_CODE   VARCHAR2(20) NOT NULL,
    SYNC_DATE   DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HSD_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER_INFO(MEMBER_ID),
    CONSTRAINT FK_HSD_HOSP FOREIGN KEY(HOSP_CODE) REFERENCES HOSPITAL_INFO(HOSP_CODE)
);

-- 4) MEASURE_ITEM (측정 항목) - 검사 결과 항목명을 위해 필요
CREATE TABLE MEASURE_ITEM (
    ITEM_CODE VARCHAR2(20) PRIMARY KEY,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    UNIT      VARCHAR2(20)
);

-- 3. 진료 기록 상세 테이블 (HOSP_SYNC_DATA의 SYNC_ID를 외래 키로 사용한다고 가정)
-- 5) DIAGNOSIS (진단명)
CREATE TABLE DIAGNOSIS (
    DIAGNOSIS_ID NUMBER(10) PRIMARY KEY,
    SYNC_ID      NUMBER(10) NOT NULL,
    DIAGNOSIS_CODE VARCHAR2(20),
    DIAGNOSIS_NAME VARCHAR2(100),
    CONSTRAINT FK_DIAG_SYNC FOREIGN KEY(SYNC_ID) REFERENCES HOSP_SYNC_DATA(SYNC_ID)
);

-- 6) MEDICATION (투약 정보)
CREATE TABLE MEDICATION (
    MEDICATION_ID NUMBER(10) PRIMARY KEY,
    SYNC_ID       NUMBER(10) NOT NULL,
    MED_NAME      VARCHAR2(100),
    DOSAGE        VARCHAR2(50),
    START_DATE    DATE,
    END_DATE      DATE,
    CONSTRAINT FK_MED_SYNC FOREIGN KEY(SYNC_ID) REFERENCES HOSP_SYNC_DATA(SYNC_ID)
);

-- 7) HEALTH_DATA (검사 결과)
CREATE TABLE HEALTH_DATA (
    HEALTH_DATA_ID NUMBER(10) PRIMARY KEY,
    SYNC_ID        NUMBER(10) NOT NULL,
    ITEM_CODE      VARCHAR2(20) NOT NULL,
    MEASURE_VALUE  NUMBER(10, 2),
    MEASURE_UNIT   VARCHAR2(20),
    MEASURE_DATE   DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HD_SYNC FOREIGN KEY(SYNC_ID) REFERENCES HOSP_SYNC_DATA(SYNC_ID),
    CONSTRAINT FK_HD_ITEM FOREIGN KEY(ITEM_CODE) REFERENCES MEASURE_ITEM(ITEM_CODE)
);


-- 4. 테스트 데이터 삽입

-- MEMBER_INFO 데이터
INSERT INTO MEMBER_INFO VALUES ('M001', '홍길동', TO_DATE('1990-05-15', 'YYYY-MM-DD'));

-- HOSPITAL_INFO 데이터 (드롭다운에 표시될 병원)
INSERT INTO HOSPITAL_INFO VALUES ('H001', '서울 종합 병원', '서울특별시');
INSERT INTO HOSPITAL_INFO VALUES ('H002', '경기 대학 병원', '경기도 수원시');
INSERT INTO HOSPITAL_INFO VALUES ('H003', '부산 미래 클리닉', '부산광역시');

-- MEASURE_ITEM 데이터 (검사 항목)
INSERT INTO MEASURE_ITEM VALUES ('IT001', '혈당 수치', 'mg/dL');
INSERT INTO MEASURE_ITEM VALUES ('IT002', '수축기 혈압', 'mmHg');
INSERT INTO MEASURE_ITEM VALUES ('IT003', '체온', '°C');

-- 시퀀스 생성 (SYNC_ID용)
CREATE SEQUENCE HOSP_SYNC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DIAGNOSIS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HEALTH_DATA_SEQ START WITH 1 INCREMENT BY 1;

-- HOSP_SYNC_DATA 및 관련 진료 기록 데이터 삽입

-- M001의 H001 병원 데이터 (2025-10-01)
INSERT INTO HOSP_SYNC_DATA (SYNC_ID, MEMBER_ID, HOSP_CODE, SYNC_DATE) VALUES (HOSP_SYNC_SEQ.NEXTVAL, 'M001', 'H001', TO_DATE('2025-10-01', 'YYYY-MM-DD'));
-- 진단
INSERT INTO DIAGNOSIS VALUES (DIAGNOSIS_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, 'D100', '급성 위염');
-- 투약
INSERT INTO MEDICATION VALUES (MEDICATION_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, '위장약A', '10mg', TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-07', 'YYYY-MM-DD'));
-- 검사 결과
INSERT INTO HEALTH_DATA (HEALTH_DATA_ID, SYNC_ID, ITEM_CODE, MEASURE_VALUE, MEASURE_UNIT, MEASURE_DATE) VALUES (HEALTH_DATA_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, 'IT001', 95.00, 'mg/dL', TO_DATE('2025-10-01', 'YYYY-MM-DD'));

-- M001의 H002 병원 데이터 (2025-11-10)
INSERT INTO HOSP_SYNC_DATA (SYNC_ID, MEMBER_ID, HOSP_CODE, SYNC_DATE) VALUES (HOSP_SYNC_SEQ.NEXTVAL, 'M001', 'H002', TO_DATE('2025-11-10', 'YYYY-MM-DD'));
-- 진단
INSERT INTO DIAGNOSIS VALUES (DIAGNOSIS_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, 'D200', '만성 두통');
-- 투약
INSERT INTO MEDICATION VALUES (MEDICATION_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, '진통제B', '5mg', TO_DATE('2025-11-10', 'YYYY-MM-DD'), TO_DATE('2025-11-30', 'YYYY-MM-DD'));
-- 검사 결과
INSERT INTO HEALTH_DATA (HEALTH_DATA_ID, SYNC_ID, ITEM_CODE, MEASURE_VALUE, MEASURE_UNIT, MEASURE_DATE) VALUES (HEALTH_DATA_SEQ.NEXTVAL, HOSP_SYNC_SEQ.CURRVAL, 'IT002', 125.00, 'mmHg', TO_DATE('2025-11-10', 'YYYY-MM-DD'));

COMMIT;