CREATE TABLE HOSPITAL_INFO (
    HOSP_CODE VARCHAR2(20) PRIMARY KEY,
    HOSP_NAME VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(200),
    CONTACT VARCHAR2(20)
);

CREATE TABLE HOSP_SYNC_DATA (
    SYNC_ID NUMBER(10) PRIMARY KEY,
    MEMBER_ID NUMBER(10) NOT NULL,
    HOSP_CODE VARCHAR2(20) NOT NULL,
    DIAGNOSIS VARCHAR2(100),
    PRESCRIPTION VARCHAR2(200),
    EXAM_RESULT VARCHAR2(300),
    VISIT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HSYNC_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER_INFO(MEMBER_ID),
    CONSTRAINT FK_HSYNC_HOSP FOREIGN KEY(HOSP_CODE) REFERENCES HOSPITAL_INFO(HOSP_CODE)
);

CREATE SEQUENCE SEQ_HOSP_SYNC_ID START WITH 1 INCREMENT BY 1;

COMMIT;