DROP TABLE MEMBER_INFO; 

CREATE TABLE MEMBER_INFO (
    MEMBER_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    BIRTH_DATE DATE,
    GENDER VARCHAR2(10),
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    CONTACT VARCHAR2(20),
    JOIN_DATE DATE DEFAULT SYSDATE,
    PASSWORD VARCHAR2(50) NOT NULL
);

--테스트용 데이터 입력 (홍길동)
INSERT INTO MEMBER_INFO (MEMBER_ID, NAME, EMAIL, CONTACT, PASSWORD) 
VALUES (1001, '홍길동', 'hong@test.com', '010-1234-5678', '1234');

COMMIT;