-- 데이터 삭제 (역순 삭제)
DELETE FROM HOSP_SYNC_DATA;
DELETE FROM HEALTH_DATA;
DELETE FROM THRESHOLD_SETTING;
DELETE FROM HOSPITAL_INFO;
DELETE FROM MEMBER_INFO;

-- 시퀀스 초기화 (삭제 후 재생성)
DROP SEQUENCE SEQ_HEALTH_DATA_ID;
DROP SEQUENCE SEQ_HOSP_SYNC_ID;
DROP SEQUENCE SEQ_THRESHOLD_ID;

CREATE SEQUENCE SEQ_HEALTH_DATA_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HOSP_SYNC_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_THRESHOLD_ID START WITH 1 INCREMENT BY 1;

COMMIT;