-- 임계치 설정 테이블 생성
CREATE TABLE THRESHOLD_SETTING (
    SET_ID NUMBER(10) PRIMARY KEY,
    MEMBER_ID NUMBER(10) NOT NULL,
    ITEM_CODE VARCHAR2(20) NOT NULL,
    UPPER_BOUND NUMBER(8, 2),
    LOWER_BOUND NUMBER(8, 2),
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_THRES_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER_INFO(MEMBER_ID)
);

CREATE SEQUENCE SEQ_THRESHOLD_ID START WITH 1 INCREMENT BY 1;

COMMIT;